# Generated by Django 3.0.2 on 2020-01-30 18:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
