# Generated by Django 2.2.4 on 2020-01-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
